# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'AZD-RWD-DEV7'
    appType: 'webAppLinux'
    WebAppName: 'demo-slot'
    deployToSlotOrASE: true
    ResourceGroupName: 'DEVRWDWEBRG7401'
    SlotName: 'staging'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    DeploymentTypeLinux: 'oneDeploy'
